server:
  port: 8762
  address: discovery2.local

eureka: 
  renewalPercentThreshold: 0.85
  environment: local
  instance: 
    hostname: discovery2.local
    appname: discovery
    preferIpAddress: false
  client: 
    health-check:
      enabled: true
    register-with-eureka: false
    fetch-registry: false
    serviceUrl: 
      defaultZone: http://srv-app-discovery:generat3aRand0mStrin5@discovery1.local:8761/eureka/

management: 
  security: 
    enabled: false

logging: 
  level: 
    be: trace
    org.springframework: warn
    com.netflix.eureka: debug
    com.netflix.discovery: debug
